version: '3'
services:
  back:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
  front:
    image: cmcornejocrespo/voting_app:0.1 
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      REDIS: back
    ports:
      - "8080:80"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]