---
- name: Install WordPress, MySQL, Nginx, PHP-FPM and netfilter rules
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python
  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress